#!/bin/sh
sudo insmod ./qxtnvram.ko cache=$1
sudo rm -fr /dev/qxtnvram
DEV=`cat /proc/devices |grep qxtnvram|awk '{print $1}'`
for D in ${DEV}; do
    sudo mknod /dev/qxtnvram c $D 0
    sudo chmod 666 /dev/qxtnvram
    break;
done
